steps:
  # 1. 도커 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/cicd-image', '.']

  # 2. Artifact Registry에 푸시하는 단계
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/cicd-image' ]

  # 3. Cloud Run 동작.
  - name: 'google/cloud-sdk'
    args: ['gcloud','run', 'deploy', 'cicd-test-run',
           '--image=asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/${tag}/cicd-image',
           '--region', 'asia-northeast1', '--platform', 'managed',
           '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
