steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ci-cd-test:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ci-cd-test:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ci-cd-test'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ci-cd-test:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
  images:
    - 'gcr.io/$PROJECT_ID/ci-cd-test:$COMMIT_SHA'