steps:
  - name: 'gradle'
    args:
      - ./gradlew
      - clean
      - build
  # 1. 도커 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/cicd-image:late', '.']

  # 2. Artifact Registry에 푸시하는 단계
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/cicd-image:late' ]

  # 3. Cloud Run 동작.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cicd-test-run-2'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/cicd-image:late'
      - '--region'
      - 'asia-northeast1'
options:
  logging: CLOUD_LOGGING_ONLY