steps:
  # mvn 설치
  - name: maven:3.8.1-openjdk-17
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true' ]

  # 1. 도커 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/${tag}/cicd-test-ar:latest', '--build-arg=JAR_FILE=target/docker-cicd-test-0.0.1-SNAPSHOT.jar', '.']

  # 2. Artifact Registry에 푸시하는 단계
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/${tag}/cicd-test-ar:latest' ]

  # 3. Cloud Run 동작
  - name: 'google/cloud-sdk'
    args: ['gcloud','run', 'deploy', 'cicd-test-run',
           '--image=asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/${tag}/cicd-test-ar:latest',
           '--region', 'asia-northeast1', 'SERVICE_REGION', '--platform', 'managed',
           '--allow-unauthenticated']
